<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Potato.Downloader.ConsoleHarness</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Potato.Downloader\Potato.Downloader.csproj" />
    <ProjectReference Include="..\Potato.ManifestApi\Potato.ManifestApi.csproj" />
    <ProjectReference Include="..\Potato.SteamMetadata\Potato.SteamMetadata.csproj" />
    <ProjectReference Include="..\Potato.Pipeline\Potato.Pipeline.csproj" />
    <ProjectReference Include="..\Potato.SlsSteam\Potato.SlsSteam.csproj" />
    <ProjectReference Include="..\Potato.Library\Potato.Library.csproj" />
    <ProjectReference Include="..\Potato.Queue\Potato.Queue.csproj" />
  </ItemGroup>

</Project>
