<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Potato.SteamMetadata</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.2" />
    <PackageReference Include="SteamKit2" Version="3.0.2" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Potato.Domain\Potato.Domain.csproj" />
  </ItemGroup>

</Project>
