<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Potato.Pipeline</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Potato.Domain\Potato.Domain.csproj" />
    <ProjectReference Include="..\Potato.Downloader\Potato.Downloader.csproj" />
    <ProjectReference Include="..\Potato.ManifestApi\Potato.ManifestApi.csproj" />
    <ProjectReference Include="..\Potato.SteamMetadata\Potato.SteamMetadata.csproj" />
    <ProjectReference Include="..\Potato.SlsSteam\Potato.SlsSteam.csproj" />
  </ItemGroup>

</Project>
